name: template-spec-linux-app-service
concurrency: template-spec-linux-app-service

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'template-specs/linux-app-service/**'

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCEGROUP_NAME: ToyReusable
  AZURE_REGION: westus3
  TEMPLATE_SPEC_NAME: linux-app-service
  TEMPLATE_SPEC_FILE_PATH: template-specs/linux-app-service/main.bicep

jobs:
  # To be added.
